# Generated by Django 3.2.9 on 2021-11-17 17:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=300, verbose_name="タイトル")),
                ("thumbnail", models.CharField(blank=True, max_length=500, null=True, verbose_name="サムネイルID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("backlog", "バックログ"),
                            ("in_progress", "進行中"),
                            ("in_reviews", "レビュー中"),
                            ("finished", "完了"),
                        ],
                        default="backlog",
                        max_length=12,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name="登録日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name="更新日時"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "タスク",
                "verbose_name_plural": "タスク",
                "db_table": "task",
                "ordering": ["pk"],
            },
        ),
    ]
