# Generated by Django 3.2.9 on 2021-11-23 10:20

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("db", "0002_auto_20211123_1727"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.CharField(max_length=500, verbose_name="コンテンツ")),
                (
                    "image_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=500), default=list, size=4
                    ),
                ),
                ("created", models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name="作成日時")),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="db.task")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "コメント",
                "verbose_name_plural": "コメント",
                "db_table": "comment",
                "ordering": ["pk"],
            },
        ),
    ]
