FROM python:3.10.7-buster

ENV DOCKERIZE_VERSION v0.6.1

RUN apt-get update \
    && apt-get install -y --no-install-recommends wget=1.20.1-1.1 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV AWS_PROFILE default

WORKDIR /app

COPY ./dockerfiles/files/start_server.sh /

CMD [ "/start_server.sh" ]
