#cloud-config
locale: ja_JP.UTF8
timezone: Asia/Tokyo

package_update: true
package_upgrade: true

users:
  - default
  - name: ubuntu
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users
  - name: training
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users
    lock_passwd: false
    passwd: $6$rounds=4096$m2OZ2XjXIMbepOAM$34a8wJfiITwiRbL6JUmZqtu1jo41tsz6wRUXpzT9bb2zr3JU.ihp9cMZpNbZ7rs4M1HItuCZMfSsIrV9gtpNk.

write_files:
- content: |
    cd /home/ubuntu/training_webapi
    /usr/local/bin/docker-compose exec backend poetry run python manage.py maintenance_mode $@
  owner: root:root
  path: /srv/maintenance.sh
  permissions: '0755'
- content: |
    #!/bin/bash
    arch=$(dpkg --print-architecture)
    # Docker
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    echo "deb [arch=${arch} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    apt update
    apt install -y docker-ce docker-ce-cli containerd.io
    systemctl start docker.service
    systemctl enable docker.service
    curl -L "https://github.com/docker/compose/releases/download/v2.11.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
    /usr/local/bin/docker-compose -f ./multipassfiles/docker-compose.yml up --build -d
  owner: root:root
  path: /srv/setup.sh
  permissions: '0755'
- content: |
    #!/bin/bash -e
    source /home/ubuntu/.bashrc
    cd /home/ubuntu/training_webapi/multipassfiles
    sudo /usr/local/bin/docker-compose logs -f backend
  owner: root:root
  path: /srv/start_server.sh
  permissions: '0755'
