name: Lint

on: [pull_request]

jobs:
  actionlint:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
    - name: Run actionlint
      uses: reviewdog/action-actionlint@d290e336d5a743810aef4404f757dc862276d2ae  # v1.73.4
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
        level: warning

  hadolint:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
    - name: run hadolint
      uses: reviewdog/action-hadolint@2d0eb7c86a0ddd94eb625485f4cc2730e105edd8  # v1.53.0
      with:
        reporter: github-pr-review
        level: warning
