name: Lint

on: [pull_request]

jobs:
  # ------------------------------------------------------------------
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: black
      uses: reviewdog/action-black@v3
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
        level: warning

  # ------------------------------------------------------------------
  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: flake8
      uses: reviewdog/action-flake8@v3
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
        level: warning

  # ------------------------------------------------------------------
  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: mypy
      uses: tsuyoshicho/action-mypy@v3
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
        level: warning

  # ------------------------------------------------------------------
  isort:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: isort
      uses: isort/isort-action@master

  # ------------------------------------------------------------------
  actionlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: actionlint
      uses: reviewdog/action-actionlint@v1
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
        level: warning

  # ------------------------------------------------------------------
  hadolint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: hadolint
      uses: reviewdog/action-hadolint@v1
      with:
        reporter: github-pr-review
        level: warning
