name: Test

on:
  push: {}

jobs:
  deps_install:
    runs-on: ubuntu-22.04

    name: Check installable dependencies

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10.5"

    - name: Bootstrap poetry
      run: |
        python -m ensurepip
        python -m pip install --upgrade pip
        python -m pip install poetry
        python -m poetry config virtualenvs.in-project true

    - name: Cache poetry dependencies
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Install dependencies
      run: |
        python -m poetry install --no-root
