name: Test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  tests:
    container: ghcr.io/nnsnodnb/swift-static-linux-sdk:6.4.0-bookworm
    runs-on: ubuntu-26.04-arm

    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
    - name: Cache
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9  # v6.1.0
      with:
        path: |
          .build/checkouts
          .build/repositories
        key: ${{ runner.os }}-swift-6.4.0-${{ hashFiles('Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-swift-6.4.0-
    - name: Install xcbeautify
      run: |
        apt-get update && apt-get install -y make
        git clone https://github.com/cpisciotta/xcbeautify.git
        cd xcbeautify
        make install
    - name: Run tests
      run: swift test | xcbeautify --renderer github-actions
