name: Test

on:
  push: {}

jobs:
  deps_install:
    runs-on: ubuntu-latest

    services:
      postgresql:
        image: postgres:16.0
        ports:
          - "5432:5432"
        env:
          POSTGRES_INITDB_ARGS: --encoding=UTF-8 --locale=C
          POSTGRES_PASSWORD: training_very_secret_password
          POSTGRES_NAME: training
          POSTGRES_USER: training
          TZ: Asia/Tokyo
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    name: Check installable dependencies

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10.5"

    - name: Bootstrap poetry
      run: |
        python -m ensurepip
        python -m pip install --upgrade pip
        python -m pip install poetry
        python -m poetry config virtualenvs.in-project true

    - name: Cache poetry dependencies
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Install dependencies
      run: |
        python -m poetry install --no-root

    - name: Migration
      run: |
        python -m poetry run python manage.py migrate
