name: Test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-24.04
    container: swift:6.3.3-bookworm

    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
    - name: Cache
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9  # v6.1.0
      with:
        path: |
          .build/checkouts
          .build/repositories
        key: ${{ runner.os }}-swift-6.3.3-${{ hashFiles('Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-swift-6.3.3-
    - name: Run tests
      run: swift test
